baseURL = "https://www.lapuntanet.com.ar/"
languageCode = "es"
theme = "tale"
title = "Primeros pasos con Hugo"
[[menu.main]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "contacto"
name = "Contacto"
title = "Contacto"
url = "/contacto/"
weight = 2
