baseURL = "https://www.lapuntanet.com.ar/"
languageCode = "es"
defaultContentLanguage = "es"
theme = "tale"

[Author]
  name = "Miguel Angel Alvarez"
  
[params]
  css = ["css/estilos.css"]

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 1
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 2

